@startuml rfc6749_oauth_flow
title OAuth2.0フロー
hide footbox

クライアント -> 認可サーバー: 1. Googleアカウントへの認可リクエストです
認可サーバー -> ユーザー: 2. Googleアカウントへのアクセスが求められています。\nOKなら認証をしてください(ユーザーID,パスワード)
ユーザー -> 認可サーバー: 3. ユーザーIDとパスワードを入力、認証します
認可サーバー -> クライアント: 4. 認可しましたので、認可コードを送ります
クライアント -> 認可サーバー: 5. 認可コード送りますので、アクセストークンをください
認可サーバー -> クライアント: 6. 認可コードを確認したので、アクセストークンを送ります
クライアント -> リソースサーバー: 7. Googleアカウントの連絡先ください。アクセストークンはこれです
リソースサーバー -> クライアント: 8. トークンの確認が終わったので、連絡先を返します
@enduml