@startuml name
title OAuth2.0フロー
hide footbox

クライアント -> リソースオーナー: 1. Googleアカウントへのアクセス権ください
リソースオーナー -> クライアント: 2. 了解。認証付与を返します
クライアント -> 認可サーバー: 3. 認可付与をもらいましたので、アクセストークンください
認可サーバー -> クライアント: 4. 了解。アクセストークンを返します
クライアント -> リソースサーバー: 5. Googleアカウントの連絡先ください。アクセストークンはこれです
リソースサーバー -> クライアント: 6. トークンは大丈夫なので、連絡先を返します
@enduml